# Generated by Django 2.2.6 on 2019-10-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsmade',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
